name: RestAssured TestNG API CI

on:
  push:
    branches: master
permissions:
  contents: write  # nÃ©cessaire pour publier sur GitHub Pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: â˜• Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: âš™ï¸ Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: ğŸ§ª Run API Tests with TestNG
        run: mvn clean test

      - name: ğŸ“¤ Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: target/extent-reports/

  deploy-report:
    if: always()
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: â¬‡ï¸ Download report artifact
        uses: actions/download-artifact@v3
        with:
          name: extent-report
          path: report/

      - name: ğŸ“„ Create index.html
        run: |
          cp report/*.html ./index.html

      - name: ğŸš€ Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./